---
- hosts: 172.31.22.167 
  become: yes
  tasks:
  - name: i want to execute linux command
    command: hostname
    resister: myresult
  
  - name: disply first task result
    debug:
       msg: "{{myresult}}"