---
- hosts: mywebservers
  become: yes
  tasks:
  - name: i want  to install webserver on ubuntu nodes only 
    apt:
     name: apache2
     state: present
    when: ansible_os_family=="Debian"

  - name: i want to install webserver on RedHat node only
    yum:
      name: httpd
      state: present
    when: ansible_os_family=="RedHat"

  - name: i want start webserver on RedHat node only
    service:
      name: httpd
      state: started
    when: ansible_os_family=="RedHat"



    
